# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

co_glasso <- function(S, pX, hpars, scr, verbose, cov_output) {
    .Call(`_coglasso_co_glasso`, S, pX, hpars, scr, verbose, cov_output)
}

co_glasso_D <- function(S, p, hpars, scr, verbose, cov_output) {
    .Call(`_coglasso_co_glasso_D`, S, p, hpars, scr, verbose, cov_output)
}

